### ISSUE TITLE
undefined method to_query 

### ISSUE THREAD

**Issue by SandeepElgbl** [Shopify/ssllabs.rb#2]
Please find the stacktrace

```
~/.rvm/gems/ruby-2.1.6/bundler/gems/ssllabs.rb-51c13d38d913/lib/ssllabs/api.rb:21:in `request': undefined method `to_query' for {}:Hash (NoMethodError)
~/.rvm/gems/ruby-2.1.6/bundler/gems/ssllabs.rb-51c13d38d913/lib/ssllabs/api.rb:50:in `info'
```

One possible solution is the params.collect as mentioned in the comments here
http://stackoverflow.com/questions/4014180/exception-with-method-to-query-missing

**Comment by SandeepElgbl** [comment]
1.16.x field addition fixes this issue

**Comment by pjgranahan** [comment]
I'm running into this same issue while attempting to run the [example](https://github.com/Shopify/ssllabs.rb#use-it-as-a-gem) on the README. I'm running Ruby 2.0.0-p598.
