### ISSUE TITLE
Release to RubyGems.org

### ISSUE THREAD

**Issue by ghost** [Shopify/ssllabs.rb#23]
It would be helpful if this was available via rubygems.org - I'm working on an application that I'm planning on releasing as a gem to ease installation, but that fact that this gem pulls from Github rather complicates that.

If you could publish it there, I would greatly appreciate it.

**Comment by EiNSTeiN-** [comment]
Done, I made this deployable via Shopify's internal deployment tooling and pushed it to rubygems: https://rubygems.org/gems/ssllabs.
