### ISSUE TITLE
Empty fields in cert and chain_cert

### ISSUE THREAD

**Issue by pjgranahan** [Shopify/ssllabs.rb#4]
While trying to run the [example](https://github.com/Shopify/ssllabs.rb#use-it-as-a-gem) on Ruby 2.0.0-p598, I encounter the following error:

```
ssllabs/api_object.rb:33:in `class_eval': ssllabs/api_object.rb:34: `@ (SyntaxError)
' is not allowed as an instance variable name
ssllabs/api_object.rb:34: syntax error, unexpected end-of-input
    from ssllabs/api_object.rb:33:in `field_methods'
    from ssllabs/api_object.rb:47:in `block in has_fields'
    from ssllabs/api_object.rb:44:in `each'
    from ssllabs/api_object.rb:44:in `has_fields'
    from ssllabs/cert.rb:3:in `<class:Cert>'
    from ssllabs/cert.rb:2:in `<module:Ssllabs>'
    from ssllabs/cert.rb:1:in `<top (required)>'
    from ssllabs.rb:10:in `require'
    from ssllabs.rb:10:in `<top (required)>'
```

This stems from two locations: `has_fields` in [cert.rb](https://github.com/Shopify/ssllabs.rb/blob/master/lib/ssllabs/cert.rb) and [chain_cert.rb](https://github.com/Shopify/ssllabs.rb/blob/master/lib/ssllabs/chain_cert.rb).

Simply removing the trailing comma seems to solve the issue.

**Comment by EiNSTeiN-** [comment]
Resolved by #5
