### ISSUE TITLE
Error on calling get_endpoint_data

### ISSUE THREAD

**Issue by idev** [Shopify/ssllabs.rb#8]
Hello,

can you please give a example how to call get_endpoint_data?
If i try it with api.get_endpoint_data(host: "www.ssllabs.com", s: "173.203.82.166", fromCache: 'on') I get in response: ssllabs.rb-07c805588307/lib/ssllabs/api.rb:35:in `request': invalid parameters (Ssllabs::InvocationError).

But the Rake Task seems to call it the same? Did i miss something?

Regards

**Comment by idev** [comment]
The Rake Task is also no longer working:
rake aborted!
Ssllabs::InvocationError: invalid parameters

**Comment by DanPatey** [comment]
Having the same problem here, any chance of a fix?

**Comment by EiNSTeiN-** [comment]
I dug into this and the error returned by the API is: `[{"message"=>"Endpoint not found"}]`. It's possible that the current API does not support this endpoint anymore.

**Comment by idev** [comment]
Hey,
i can not reproduce the issue.
Can you post some stack trace? Which Version of the gem are you using?

**Comment by EiNSTeiN-** [comment]
You are the one who reported it, so I'm not sure what you mean by "can't reproduce" ?

**Comment by EiNSTeiN-** [comment]
Let's close this if this is resolved.
